# Generated by Django 5.0.2 on 2024-02-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfume', '0002_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img',
        ),
    ]
