# Generated by Django 5.0.2 on 2024-02-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfume', '0003_delete_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='perfume',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
