# Generated by Django 5.0.2 on 2024-02-18 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfume', '0006_delete_perfume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=100)),
                ('PDescription', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.FloatField(null=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfume.catagory')),
            ],
        ),
    ]
